services:
  edge-caddy:
    image: caddy:2.8-alpine
    container_name: callitcureit-edge-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - edge-caddy-data:/data
      - edge-caddy-config:/config
    networks:
      - callitcureit-dev_default
      - callitcureit-tst_default
      - callitcureit-prd_default

volumes:
  edge-caddy-data:
  edge-caddy-config:

networks:
  callitcureit-dev_default:
    external: true
  callitcureit-tst_default:
    external: true
  callitcureit-prd_default:
    external: true